//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualityControl.xUnit.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualityControl.xUnit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] decryptedFile {
            get {
                object obj = ResourceManager.GetObject("decryptedFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Wyszukuje zlokalizowany zasób typu System.Byte[].
        /// </summary>
        internal static byte[] encryptedFile {
            get {
                object obj = ResourceManager.GetObject("encryptedFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu JZlD5JFMCc+zuaUkyiYOUw4ejf9b8dZafEyQmT5bXdml7owPzgHBH+SOHsb+5F7mZWdkYn+VejFxkR0CkgOqEfBFhKI8ADuSFlvL+r1Fyc8j1y6pK58jKi8RbDJHtrR7ylek8E1J17lV5KLvcNjltkbQ9+3YDNZwzSlDfcYLrJ4VK94Qh44owww4y5HK+E7aikboIWp1jL4HP6aeJUwa91PiJewvnKpPk+nuOCZY5zDpYtL6mH5bhiB1LiDNAmQJaU1EJQokPo9/dK+bOdZfTRKBueX1K4QyT7MWxFSx+W+55HjKzwcv9t6B/95Sxnl6wtVAkIf7rVcAeNnmjj+4zlrgYFlaBU63JdrZGmKb3eti5jott82sbK5tnJvVSTTbAG+rDthMia7zMLLSCdWfFHKCxxoBNfhQDad5zi8d3RLipsmF8+EzBke1dvfxre0aNaHwIuEj7wI39TDemCNcsKLxZw4k8EDI4NNsyMLJTR1zZgErftAtoBATXiJKsS/d [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string profileFile {
            get {
                return ResourceManager.GetString("profileFile", resourceCulture);
            }
        }
    }
}
